name: Add issues to dev project

on:
  issues:
    types:
      - labeled

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          # You can target a project in a different organization
          # to the issue
          project-url: https://github.com/users/MasterZelgadis/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: needs-triage
